name: comsrv
description: Client implementation for comsrv
version: 2.3.1
homepage: https://github.com/raffber/comsrv
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  broadcast_wsrpc:
    git:
      url: https://github.com/raffber/wsrpc.git
      ref: 2b5f10a4251a72afbebd74c1701423eef6cf7aea
      path: dart/broadcast_wsrpc
  uuid: ^3.0.6
  quiver: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0