name: comsrv
description: Client implementation for comsrv
version: 0.0.1
homepage: https://github.com/raffber/comsrv
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  broadcast_wsrpc:
    git:
      url: https://github.com/raffber/wsrpc.git
      ref: release/0.1.0
      path: dart/broadcast_wsrpc
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0