name: comsrv
description: Client implementation for comsrv
version: 0.0.1
homepage: https://github.com/raffber/comsrv
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  wsrpc:
    git:
      url: https://github.com/raffber/wsrpc.git
      ref: release/v1.1.1
      path: dart/wsrpc
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0