apiVersion: v1
kind: Service
metadata:
  name: comsrv
  labels:
    app: comsrv
spec:
  type: LoadBalancer
  selector:
    app: comsrv
  ports:
    - name: websockets
      port: 5902
      targetPort: 5902
    - name: http
      port: 5903
      targetPort: 5903
