[tool.poetry]
name = "comsrv"
version = "2.1.1"
description = ""
authors = ["Raphael Bernhard <beraphae@gmail.com>"]
packages = [
    { include = "comsrv", from = "python" },
]

[tool.poetry.dependencies]
python = ">=3.8, <3.12"
broadcast_wsrpc = {git="https://github.com/raffber/wsrpc.git", rev="f0a63fcfb680c93439ce8e8352143473f3bfa765", subdirectory="python"}
aiohttp = "^3.7"
numpy= "^1.22"

[tool.poetry.dev-dependencies]
black = "23.3"
mypy = "^1.2.0"
poetry = "^1.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
