[package]
name = "comsrv"
version = "0.1.0"
authors = ["Raphael Bernhard <beraphae@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.1.10"
tempfile = "3.1.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
lazy_static = "1.4.0"
thiserror = "1.0.20"
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "0.2.22", features = ["sync", "time", "rt-core", "blocking", "macros"]}
wsrpc = {path = "../wsrpc"}
clap = "2.33.3"
env_logger = "0.7.1"
log = "0.4.11"
url = "2.1.1"
tokio-modbus = "0.4.0"
tokio-serial = "4.3.3"
async-trait = "0.1.40"
async-std="1.6"
futures="0.3.7"
base64 = "0.13.0"
async-vxi11 = {git = "https://github.com/raffber/async-vxi11.git", rev = "453cb1c"}
async-can = {path = "../../async-can"}
byteorder = "1.3"
