[package]
name = "comsrv"
version = "0.1.0"
authors = ["Raphael Bernhard <beraphae@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.1.10"
tempfile = "3.1.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
lazy_static = "1.4.0"
thiserror = "1.0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "^1", features = ["sync", "time", "rt", "macros"] }
wsrpc = { path = "../wsrpc" }
clap = "2.33.3"
env_logger = "0.7.1"
log = "0.4.11"
url = "2.1.1"
uuid = "0.8.2"
tokio-modbus = "0.5.0"
tokio-serial = "5.4.1"
async-trait = "0.1.40"
futures = "0.3.7"
base64 = "0.13.0"
async-vxi11 = { git = "https://github.com/raffber/async-vxi11.git", rev = "0371e960f0a3018db83fabf4d773f585959e6e06" }
async-can = { git = "https://github.com/raffber/async-can.git", rev = "87780eb0ddc01060185c6c7e2461686dc66fe563" }
byteorder = "1.3"
bitvec = "0.20.1"
hidapi = "1.2.6"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
debug = 0
