[package]
name = "comsrv"
version = "0.1.0"
authors = ["Raphael Bernhard <beraphae@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.1.10"
tempfile = "3.1.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
lazy_static = "1.4.0"
thiserror = "1.0.20"
futures = "0.3.5"
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "0.2.22", features = ["sync", "time", "rt-core", "blocking"]}
wsrpc = {path = "../wsrpc"}
clap = "2.33.3"
env_logger = "0.7.1"
log = "*"
