[package]
name = "comsrv"
version = "1.3.0"
authors = ["Raphael Bernhard <beraphae@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.1.10"
tempfile = "3.1.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
lazy_static = "1.4.0"
thiserror = "1.0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "^1", features = ["sync", "time", "rt", "macros", "rt-multi-thread"] }
wsrpc = { git = "https://github.com/raffber/wsrpc.git", tag = "release/v1.0.0" }
clap = "2.33.3"
env_logger = "0.7.1"
log = "0.4.11"
url = "2.1.1"
uuid = "0.8.2"
tokio-modbus = "0.5.0"
tokio-serial = {version = "5.4.3", features = ["libudev"]}
async-trait = "0.1.40"
futures = "0.3.7"
async-vxi11 = { git = "https://github.com/raffber/async-vxi11.git", rev = "0371e960f0a3018db83fabf4d773f585959e6e06" }
async-can = { git = "https://github.com/raffber/async-can.git", rev = "a31f726fb4dc76bb2cbb49b65d921ea134e71766" }
# async-ftdi = {git = "https://github.com/raffber/async-ftdi.git", rev = "d6d0426d70c9aa503ee679f8eaeeedb5233c1b8b"}
async-ftdi = {path = "../../async-ftdi"}
byteorder = "1.3"
bitvec = "0.20.1"
hidapi = {version = "1.2.6", default-features = false, features = ["linux-static-hidraw"] }
comsrv_protocol = { path = "../comsrv_protocol" }

[dependencies.libftd2xx]
version = "0.32"
features = ["static"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
debug = 0

[target.'cfg(unix)'.dependencies]
libc = "0.2"
