name: CD

on:
  push:
    tags:
      - 'release/*'
  workflow_dispatch:

jobs:
  run-build:
    uses: ./.github/workflows/ci.yml
  release:
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - uses: actions/checkout@v3

      - name: Download workflow artifacts
        uses: actions/download-artifact@v3
        with:
          name: comsrv
          path: out

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: out/*

