name: CI

on:
  push:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Version Check
      run: ci/check-version.sh

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: comsrv-agent:latest

    - name: Run Build
      run: docker run -v ${{ github.workspace }}:/workspace comsrv-agent ci/build-ci.sh
    - name: Run Test
      run: docker run -v ${{ github.workspace }}:/workspace comsrv-agent ci/test-ci.sh
    - name: Build python wheel
      run: docker run -v ${{ github.workspace }}:/workspace comsrv-agent ci/build-wheel.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: comsrv
        path: |
          out/comsrv
          out/comsrv.exe
          out/*.whl
          
