name: CI

on:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Version Check
        run: ci/check-version.sh

      - name: Get Version
        id: version
        run: echo ::set-output name=version::$(ci/get-version.sh)

      - name: Setup buildx backend for docker
        uses: docker/setup-buildx-action@v1

      - name: Build builder docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: comsrv-agent:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: deploy/Dockerfile
          tags: raffber/comsrv:${{ steps.version.outputs.version }}

      - name: Run Build
        run: docker run -v ${{ github.workspace }}:/workspace comsrv-agent ci/build-ci.sh

      - name: Run Test
        run: docker run -v ${{ github.workspace }}:/workspace comsrv-agent ci/test-ci.sh

      - name: Build python wheel
        run: docker run -v ${{ github.workspace }}:/workspace comsrv-agent ci/build-wheel.sh

      - name: Build python wheel
        run: docker run -v ${{ github.workspace }}:/workspace comsrv-agent ci/check-python.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: comsrv
          path: |
            out/comsrv
            out/libcomsrv.so
            out/comsrv.exe
            out/comsrv.dll
            out/comsrv.dll.lib
            out/*.whl
