name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger build
        uses: ./.github/workflows/build.yml
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2.22.0
        with:
          path: ${{ github.workspace }}/out
          commit: e277b23354573288d66a2fbc91af60c197ae6ecc
          workflow: build.yml
          github_token: ${{secrets.GITHUB_TOKEN}}
          artifact_name: comsrv
          workflow_conclusion: success
      - run: pwd
      - run: ls
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: out/comsrv/*

