name: Release

on:
  workflow_dispatch:

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2.22.0
        with:
          path: ${{ github.workspace }}/out
          commit: ${{ env.GITHUB_SHA }}
          workflow: build.yml
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: comsrv
          workflow_conclusion: success
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: out/comsrv/*

